spring:
  application:
    name: movie-catalog-service
  cloud:
    config:
      uri: http://localhost:8888
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8081

  management:
    endpoints:
      web:
        exposure:
          include: "*"

  resilience4j.circuitbreaker:
    configs:
      getCatalog:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
